// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU8mwVLfs8v7WrTY3kLLA2GiAiWxwY2ds',
    appId: '1:468268824625:web:bb4e725032ad4702523d10',
    messagingSenderId: '468268824625',
    projectId: 'male-store-ab1d1',
    authDomain: 'male-store-ab1d1.firebaseapp.com',
    storageBucket: 'male-store-ab1d1.firebasestorage.app',
    measurementId: 'G-FMWLTHV6W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvLu6ITubDlTF_mHutAWO0S19enlsOhA',
    appId: '1:468268824625:android:701d785a4fedde51523d10',
    messagingSenderId: '468268824625',
    projectId: 'male-store-ab1d1',
    storageBucket: 'male-store-ab1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsbQYp9gS6o4-UcK6WDdVEnxqFWgNg1k',
    appId: '1:468268824625:ios:e82cb27e2d48e1d0523d10',
    messagingSenderId: '468268824625',
    projectId: 'male-store-ab1d1',
    storageBucket: 'male-store-ab1d1.firebasestorage.app',
    iosBundleId: 'com.example.maleClothingStore',
  );
}
